### ISSUE TITLE
Hello,dear friend,i can use this miner on 80ti,and 3.5G/S per GPU,but 1080 only 400MH/S

### ISSUE THREAD

**Issue by icekale** [PhamHuong92/VeoMiner#1]
Hello,dear friend,i can use this miner on 80ti,and 3.5G/S per GPU,but 1080 only 400MH/S,and 1065 only 150MH/S,could you help me?thank you very much

**Comment by PhamHuong92** [comment]
Run mismatched GPU models in separate command instances. Only use same GPU models in single command instance.

Try many blocksize and numblocks values for best speed. Ask Amoveo Telegram group for suggestions on your GPU model optimal values.
