### ISSUE TITLE
AMD hashrate issue multiple GPUs single process 1.2.5

### ISSUE THREAD

**Issue by seravitae** [PhamHuong92/VeoMiner#10]
On RX570 AMD cards, using "ALL" for all gpus on a single thread gives a hashrate of 178MH/s per card.

Spawning a single process using successive 0, 1, 2, 3 (one process per gpu) the hashrate is >1.4GH/s per card.

There is either a math problem in the display of hashrate (appears to be divided by the number of cards) or something else is wrong.

**Comment by PhamHuong92** [comment]
AMD asynchronous kernel not yet optimal. Single process each AMD GPU best workaround until fixed.

**Comment by archills** [comment]
Is there any progress about this problem?  I am struggling to open 6 instances with the  Intel G3930 CPU.

**Comment by PhamHuong92** [comment]
IP has reported that Windows 10 with drivers 18.3.4 adrenaline, gpu compute mode is running 6 rx580 at 1.8gh/s on a single instance of veominer with the new kv=5 and sk=2 arguments in veominer 2.3.

Closing bug as fixed
