### ISSUE TITLE
failed clGetDeviceIDs err = -32

### ISSUE THREAD

**Issue by skifreak24** [PhamHuong92/VeoMiner#12]
This is what i get when launching the miner. I have another PC with a single 1060 and it says platformId: 0 before "All GPU Devices: 4" Seems like something is going wrong with the platform selection? i have tried p=0, p=1, and p=2 but the line before the devices all ways says 2.

WorkerId:
DeviceIds: 0all
BlockSize: 64
NumBlocks: 100
SuffixMax: 65536
PlatformId: 0
AutoLocal: 0
PoolUrl: http://amoveopool2.com/work
SyncKernel: 0
KernelVersion: 4
DevFeePercent: 1
RandomSeed: MINER2-Thu May 24 23:04:38 2018

-----------------------------------------------------------------
**PlatformId: 2,** All GPU Devices: 4
Device: 0, Name: GeForce GTX 1080
Device: 1, Name: GeForce GTX 1060 3GB
Device: 2, Name: GeForce GTX 1060 3GB
Device: 3, Name: GeForce GTX 1070 Ti
Failed clGetDeviceIDs err = -32.

**Comment by miller46** [comment]
Try a different platform ID.  Try setting it to 1

**Comment by PhamHuong92** [comment]
I see DeviceIds: 0all
Is it "0all"?
I think a "0all" deviceIds might be problem.

Try set p=2 d=all

Please report if that works or not works. Thank you for good details on configuration print out.

**Comment by skifreak24** [comment]
Thanks for the responses. It appears that the problem was a missing windows update. Installed all windows updates and everything now works without issue.
