### ISSUE TITLE
Hi, Could you please give me your source code? 

### ISSUE THREAD

**Issue by swordpool** [PhamHuong92/VeoMiner#15]
Hi, Could you please give me your source code? i am targeting to study only, I promise you that i would never to use for business operations. If that would be okay please send it to my email : 29977000@qq.com, thank you.

**Comment by swordpool** [comment]
I am so hopeful to know that how can you get so high hash-rates?

**Comment by swordpool** [comment]
I'd like to know how a single GTX1060/6G can reach 1.68GH/s. My program can only reach 580MH/s. I'd like to see what optimization you've made. look forward your reply.

**Comment by PhamHuong92** [comment]
Sorry, no code for veominer available. Amoveo is single sha256 so much faster than bitcoin hash rate.
