### ISSUE TITLE
libcpprest.so.2.8 error

### ISSUE THREAD

**Issue by adrienneoui** [PhamHuong92/VeoMiner#16]
error while loading shared libraries: libcpprest.so.2.8: cannot open shared object file: No such file or directory

Fix: sudo apt install libcpprest

**Comment by PhamHuong92** [comment]
Please use the Veominer that matches your Ubuntu version. Releases has build for Ubuntu 16, 17, and 18.

If you have Ubuntu 18, try this:
https://github.com/PhamHuong92/VeoMiner/releases/download/2.7/veominer_Ubuntu18_2.7.tar.gz
