### ISSUE TITLE
libcpprest dependency

### ISSUE THREAD

**Issue by shinybrar** [PhamHuong92/VeoMiner#2]
## Issue
Currently, `veominer` requires `libcpprest=2.9` which is only available for `Ubuntu 17.10-artful` release. Currently all major stable Linux OS releases are using `libcpprest=2.8`. As a result, `veominer` cannot run on current linux releases.

# Resolution
 It could be beneficial to rollback the library requirement to `libcpprest=2.8`

**Comment by PhamHuong92** [comment]
Fixed
https://github.com/PhamHuong92/VeoMiner/releases/download/1.2/veominer_Ubuntu16_1.2.tar.gz
