### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by BobbyGR** [PhamHuong92/VeoMiner#20]
Had a request to add this to AIOMiner, just curious if you have an API to tap in that I might not have seen poking around it.

**Comment by PhamHuong92** [comment]
Thank you for adding VeoMiner to AIOMiner. VeoMiner does not have internal API. Amoveo pools have API option available for worker monitors.

**Comment by PhamHuong92** [comment]
Veominer 2.9 has API added:
https://github.com/PhamHuong92/VeoMiner/releases/tag/2.9

GET http://localhost:11363/hashrate
GET http://localhost:11363/shares
