### ISSUE TITLE
Can't change the pool

### ISSUE THREAD

**Issue by zack-bitcoin** [PhamHuong92/VeoMiner#3]
People want to use this pool: http://159.65.120.84:8085/main.html

But the miner is not letting them switch pools.
If we all use the same pool, it is bad for the network, it makes it centralized.
This is bad for the price of Veo.

**Comment by PhamHuong92** [comment]
Zack threaten reverse engineer crime. You make crime at me bad for Veo price.

Yes need fix. Work busy. Open for tracking.

**Comment by PhamHuong92** [comment]
veominer 1.3 fix

**Comment by zack-bitcoin** [comment]
Great. Thank you.

**Comment by zack-bitcoin** [comment]
I P from chat says:
could not get 1.3 miner to properly work on amd rig (without hanging and with good hashrate). while 1.2 works well. 1.3 leaks memory on amd or smth

It seems like the new version has a problem.
