### ISSUE TITLE
cannot change pools

### ISSUE THREAD

**Issue by zack-bitcoin** [PhamHuong92/VeoMiner#7]
https://www.reddit.com/r/Amoveo/comments/8g5t7h/mining_pool_issues/

They are saying that Version 1.3 only works with AmoveoPool2.

It is important for the health of the network that other pools work too.
If you do not fix this, we will disable your software, or use reverse engineering to turn off your reward.

**Comment by zack-bitcoin** [comment]
https://github.com/PhamHuong92/VeoMiner/issues/3

I first reported this problem 3 weeks ago, and you continue to refuse to fix it.

**Comment by PhamHuong92** [comment]
You threats not welcome to me. I investigate.

**Comment by zack-bitcoin** [comment]
We edited the byte code. Now it connects to a different pool, but it does not pay you: https://github.com/zack-bitcoin/veominer_reverse_engineering

**Comment by PhamHuong92** [comment]
Need fix. Add AutoLocal break url argument.

**Comment by PhamHuong92** [comment]
1.4 fix. 

Now any URL with Amoveopool2.com/work json protocol.
