### ISSUE TITLE
Bad developer address

### ISSUE THREAD

**Issue by zack-bitcoin** [PhamHuong92/VeoMiner#8]
Now Pham Huong is not being paid.
This address is invalid: v8X+pcYXf+kLyaTW0F6W228vqIQPKrXegIJU0SoVn4Wr5EIYUOeHGwo7AhNuCjfIz7+fUpgqNSTPQsmCfxpieeQ=

Addresses must start with a "B".

Pham Huong, you can make a lot of money from this software.
If you fix your software, you will start getting paid.

This page can generate pubkey/private key combinations. Make sure to save your private key. http://159.65.120.84:8080/wallet.html

**Comment by PhamHuong92** [comment]
Thank you report. Fix soon.

**Comment by PhamHuong92** [comment]
1.4 fix. Thank you report.
